categories:
- definition_info
conversations:
- - whats the definition of $
  - the definition of {} is {}  
- - tell me the definition of $
  - the definition of {} is {}  
- - whats the meaning of $
  - the definition of {} is {}  
- - what does $ mean
  - the definition of {} is {}  
- - definiton of $
  - the definition of {} is {}  