categories:
- news_info
conversations:
- - What news?
  - Here are some news {}  
- - tell me news about $
  - Here are some news about {} {}
- - What news from $
  - Here are some news from {} {}
- - news from $
  - Here are some news from {} {}
- - news about $
  - Here are some news about {} {} 
- - tell me some news
  - Here are some news {}
- - some trending news
  - Here are some news {}    